### ISSUE TITLE
Support ignoring unknown fields

### ISSUE THREAD

**Issue by leostera** [serde-ml/serde#17]
We have an attribute called `error_on_unknown_fields` that we want to use to skip any fields that are not known. This would help parse anything coming from uncontrolled sources, where new fields may be added without notice.

Essentially, this is a type-level attribute:

```ocaml
type user = {
  name: string
}
[@@deriving serialize, deserialize]
[@@serde { error_on_unknown_fields = false }]
```

The expected behavior is that the visitors created for translating ints and strings and identifiers into tags will not return an `Error` if they don't match the expected fields, and instead will return a new tag that can be used to skip the field instead.

Note that some formats may have an easier or harder time skipping a field when we don't know the shape it has, so please have a look at how Rust's serde_json and serde_toml do this.

**Comment by tjdevries** [comment]
From what I can tell, in serde it's actually:

```
#[serde(deny_unknown_fields)]
Always error during deserialization when encountering unknown fields. When this attribute is not present, by default unknown fields are ignored for self-describing formats like JSON.

Note: this attribute is not supported in combination with [flatten](https://serde.rs/field-attrs.html#flatten), neither on the outer struct nor on the flattened field.
```
