### ISSUE TITLE
@@deriving serializer, deserializer

### ISSUE THREAD

**Issue by lindig** [serde-ml/serde#9]
I think these names are too generic because this won't be the last framework to provide serialization and de-serialization and thus create tension down the line. I would suggest to use some _serde_  prefix to avoid this before you are forced to do this later. I think it's quite common to want both directions and that could be offered by a single `@@deriving serde`.

**Comment by leostera** [comment]
Hi @lindig! I don't see this being an issue with other ppx's like `show` and I'd rather this read as natural as possible for users. If you have a conflicting ppx that won't work with this one, and you want to use them both at the same time, then there's still options you can use to avoid using both ppx's in the same module.

Closing this for now, thanks for the feedback! 🙏🏼
